#include <stdio.h>

void main()
	{printf("\n                                 hatthefuc \n"                                        
"                              kdidyoujustfuckin\n"                                     
"                          gsayaboutme,youlittlebit\n"                                  
"                  ch?I’llhaveyouk           nowIgrad\n"                                
"               uatedtopofmyc                  lassint\n"                               
"             heNavySeals,and                   I’vebe\n"                               
"             eninvolvedinnume                   rouss\n"                               
"             ecretraidso nAl-Qu    aeda,andIha  veove\n"                               
"             r300confirmedkills. Iamtrainedingor illa\n"                               
"             warfareandI’mthet  opsniperintheentireUS\n"                               
"            armed  forces.Youa  renothingtomebutjusta\n"                               
"           nothertarget.Iwillwi peyouthefuc koutwithp\n"                               
"          recisionthelikesofw   hichhasneverbeenseenb\n"                               
"         eforeonthisEarth,markmyfuckingwords.  Youth\n"                                
"        inkyo          ucangetawaywithsay     ingtha\n"                                
"       tshit                      tomeove     rtheIn\n"                                
"      ternet                                 ?Think\n"                                 
"     again,                                 fucker\n"                                  
"    .Aswes                                  peakIa\n"                                  
"    mcont                      acti        ngmyse\n"                                   
"   cret                      netwo rko   fspies\n"                                    
"  acro                      sstheUSAan  dyour                         IPisbeing\n"   
"  trace                      drightnow  soyou                        betterprepar\n"  
"  efort                     hestorm,ma ggot.                       Thesto    rmth\n"  
"  atwip                     esoutthep  athet                     iclittl    ethin\n"  
"   gyouc                    allyourli  fe.You                   ’refuck     ingde\n"   
"   ad,ki                    d.Icanbe   anywhere,anytime,and   Icankil     lyoui\n"     
"    nove                   rsevenhu    ndredways,andthat’sjustwithm      ybare\n"      
"    hand                   s.Noton     lyamI   exten   sivelytrai      nedinu\n"       
"    narm                  edcombat      ,bu   tIhaveaccesstothe      entire\n"         
"    arsen               aloft heUni         tedStatesMarineCor     psandIw\n"          
"     illu             seitt  oitsful         lextenttowipeyourmi   serablea\n"         
"     ssoff            thefaceoftheco                     ntinent,    youlittle\n"      
"      shit.            Ifonlyyoucou              ldha       veknow  nwha tunho\n"      
"      lyretr              ibut                   iony        ourlit  tle“clev\n"       
"       er”com                                men              twasa    bout\n"         
"        tobringd                            ownu              ponyo     u,ma\n"        
"           ybeyouw                          ould              haveheldyourfu\n"        
" cki        ngtongue.B                       utyo           ucouldn’t,youdi\n"         
"dn’t,an    dnowyou’repayingt                  hep         rice,yo    u\n"              
"goddamnidiot.I willshitfuryalloveryo           uand    youwill\n"                      
"drow ninit.You’refu    ckingdead,kiddo .Whatthefuckdidyoujus\n"                        
" tfuc  kingsayabo         utme,youlit tlebitch?I’llhaveyo\n"                           
"  ukno   wIgrad         uatedtopofmy class intheNavySe\n"                              
"   als,andI’v           ebeeninvolv  edin\n"                                           
"    numerou             ssecretr   aids\n"                                            
"      onA               l-Quae    da,a\n"                                             
"                          ndIhav  eove\n"                                              
"                           r300confir\n"                                               
"                            medkill\n"                                                
"                               s.I\n");
}      
